name: Publish plugins to release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-plugins:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: artifacts.${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
          /usr/local/bin/yq --version
      - name: Publish untracked plugins
        run: |
          plugins=$(yq e -o=j -I=0 '.plugins[]' ./charts/opensearch-dashboards/plugins/manifest.yaml)
          mkdir .downloads
          curl --version
          for line in $plugins; do
            name=$(echo "$line" | yq e '.name' -)
            url=$(echo "$line" | yq e '.url' -)
            echo "Name: $name"
            echo "URL: $url"
            if [[ $url != "${{ github.server_url }}/${{ github.repository }}"* ]]; then
              curl -o ./.downloads/$name.zip -L $url
            fi
          done
      - name: Create Release Tag
        run: |
          git tag ${{ env.RELEASE_TAG }}
          git push origin ${{ env.RELEASE_TAG }}
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: ./.downloads/*
          tag_name: ${{ env.RELEASE_TAG }}
      - name: Update manifest
        run: |
          artifacts=$(echo "${{ steps.release.outputs.assets }}" | yq e -o=j -I=0 '.[]' -)
          for line in $artifacts; do
            echo "LINE: $line"
            filename=$(echo "$line" | yq e '.name' -)
            echo "filename: $filename"
            # filename without extension which should be the plugin name
            name="${filename%.*}"
            echo "Name: $name"
            url=$(echo "$line" | yq e '.browser_download_url' -)
            echo "URL: $url"
            name="$name" url="$url" yq -i '.plugins |= map(select(.name == strenv(name)).url=strenv(url))' ./charts/opensearch-dashboards/plugins/manifest.yaml
          done
          cat ./charts/opensearch-dashboards/plugins/manifest.yaml
