---
global:
  dockerRegistry: public.ecr.aws

image:
  repository: "m4z9c2w0/opensearch-treadstone"
  tag: "4816141528"
  pullPolicy: "IfNotPresent"

majorVersion: "2"

nodeGroup: "machinelearning"

roles:
  - ml

replicas: 2

opensearchJavaOpts: "-Xmx16G -Xms16G"

resources:
  requests:
    cpu: "4"
    memory: "16Gi"
  limits:
    nvidia.com/gpu: 1

tolerations:
  - key: "GPU"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

nodeSelector:
  GPU: "true"
