---
image:
  repository: "opensearchstaging/opensearch"
  tag: "2.7.0"
  pullPolicy: "IfNotPresent"

nodeGroup: "machinelearning"

roles:
  - ml

replicas: 2

opensearchJavaOpts: "-Xmx16G -Xms16G"

resources:
  requests:
    cpu: "4"
    memory: "32Gi"
